name = "FastSpike"
uuid = "1dba01d4-f71c-4248-8233-6d2363294db3"
authors = ["Mahbod Nouri"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
